import Head from "next/head";
import { Col, Container, Row } from "react-bootstrap";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>باشگاه دلفین گربدان</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/dolfin.png" />
      </Head>

      <main className={styles.main}>
      <motion.div
        initial="hidden"
        animate="visible"
        variants={{
          hidden: {
            scale: 0.8,
            opacity: 0,
          },
          visible: {
            scale: 1,
            opacity: 1,
            transition: {
              delay: 0.6,
            },
          },
        }}
      >


        
        <Container fluid className={styles.cont}>
          <Row>
            <Col className={styles.hom1} sm={6}>
              <Col className={styles.hom11} md={12}>
                <p className={styles.textdolfin}>
                  ⚽ باشگاه فرهنگی ورزشی دلفین گربدان ⚽{" "}
                </p>
              </Col>
            </Col>
            <Col className={styles.hom2} sm={5}>

              

              
            </Col>
          </Row>
        </Container>





        </motion.div>
      </main>
    </div>
  );
}
