import Head from "next/head";
import { Col, Container, Row } from "react-bootstrap";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>

        
        <title>باشگاه دلفین گربدان</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="images/dolfin.png"
        />
      </Head>

      <main className={styles.main}>
        <Container fluid className={styles.cont}>
          <Row>
            <Col className={styles.hom1} sm={6}>
              <Col className={styles.hom11} md={12}>
                <p className={styles.textdolfin}>⚽ باشگاه فرهنگی ورزشی دلفین گربدان ⚽ </p>
              
              </Col>
            </Col>
            <Col className={styles.hom2} sm={5}>
           
            </Col>
          </Row>
        </Container>
      </main>
    </div>
  );
}
